---
- name: Update windows host
  hosts: all
  gather_facts: false
  vars:
    log_path: "C:\\ansible_wu.txt"
    category_names:
      - "CriticalUpdates"
      - "SecurityUpdates"
      - "UpdateRollups"
      - "Updates"
      - "Drivers"
      - "FeaturePacks"
      - "ServicePacks"
      - "Tools"
    reboot_timeout: 3600

  tasks:
    - name: Search-only, return list of found updates (if any), log to specified path
      ansible.windows.win_updates:
        category_names: "{{ item }}"
        state: searched
        log_path: "{{ log_path }}"
      register: response
      loop: "{{ category_names }}"
      loop_control:
        label: "{{ item }}"

    - name: Check if updates are found and log the details
      ansible.builtin.debug:
        msg: "Updates found for category {{ item.item }}: {{ item.found_update_count }}"
      loop: "{{ response.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Install all updates and reboot if necessary
      ansible.windows.win_updates:
        category_names: "{{ item.item }}"
        reboot: true
        reboot_timeout: "{{ reboot_timeout }}"
      register: update_response
      loop: "{{ response.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Wait for system to become available
      ansible.builtin.wait_for_connection:
        delay: 60
        timeout: 360
