---
- name: update windows host
  hosts: all
  gather_facts: false
  vars:
    log_path: "C:\\ansible_wu.txt"
    reboot_timeout: 3600
    
  tasks:
    - name: Search-only, return list of found updates (if any), log to specified path
      ansible.windows.win_updates:
        category_names: "{{ item }}"
        state: searched
        log_path: "{{ log_path }}"
      register: response
      loop: "{{ category_names }}"
      loop_control:
        label: "{{ item }}"

    - name: Check if updates are found and log the details
      debug:
        msg: "Updates found for category {{ item }}: {{ response.results[item.index].found_update_count }}"
      loop: "{{ response.results }}"
      loop_control:
        index_var: index
      when: item.found_update_count > 0

    - name: Install all updates and reboot if necessary
      ansible.windows.win_updates:
        category_names: "{{ item }}"
        reboot: yes
        reboot_timeout: "{{ reboot_timeout }}"
      register: update_response
      loop: "{{ category_names }}"
      loop_control:
        label: "{{ item }}"
      when: response.results[item.index].found_update_count > 0

    - name: Check the status of the update installation
      debug:
        msg: "Update installation for category {{ item }}: {{ update_response.results[item.index] }}"
      loop: "{{ update_response.results }}"
      loop_control:
        index_var: index
